apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
  namespace: production
  labels:
    app: tic-tac-toe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: tic-tac-toe
          image: ghcr.io/garbaa/devsecops-demo:sha-bd0e56c0fed92610d110af50891ce7882ea68bb1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
